### PR TITLE
Eliminate kve bookkeeping in controllers

### PR DESCRIPTION
**Pull request by benjaminapetersen**
@rhamilto @jwforres

Eliminates a bunch of stuff, yay.

### CODE REVIEW

**Comment by jwforres** [comment]
This looks so much better, I'm seeing one more minor fix to add to this so @rhamilto hold off on merging for the moment

**Comment by benjaminapetersen** [comment]
Yeah. I still wish there was a good way to reduce a few more things, but it'll do i think.

**Comment by benjaminapetersen** [comment]
updated

**Comment by jwforres** [comment]
LGTM @rhamilto can you merge

**Comment by benjaminapetersen** [comment]
updated again. named the function something sensible this time. i think. 😀

**Pull request merged**
